### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kingsmen732**

### CODE REVIEW

**Comment by salma2vec** [comment]
Hey there! Can you please make sure to upload the HTML code in the appropriate folder labeled "assignment 1"? This will help keep everything organized and make it easier for us to review and provide feedback. Thanks!

**Comment by salma2vec** [comment]
Also, make sure to check out the sample code that has been uploaded in the "assignment 1" folder. This will give you an idea of the naming practices and commit message style that we prefer. It's important to keep consistency throughout the project, so please keep that in mind when submitting your code.

**Comment by kingsmen732** [comment]
have i uploaded the file correctly this time?

**Comment by salma2vec** [comment]
Add `align-items: center` to the parent container's CSS style for better vertical alignment of the gender options and we are good to go!

**Comment by LahariDurgaKetha** [comment]
Can u plz tell me whether my file is uploaded or not?

**Comment by kingsmen732** [comment]
new changes have been done to the file  , confirm if all okeuio @IdealisticINTJ

**Comment by salma2vec** [comment]
Hi there, 
Edit: Upload the code in the "assignment 1" folder. Thanks!

**Pull request closed without merging**
