### PR TITLE
Submission 1 - Lahari Durga Ketha

### PR DESCRIPTION
**Pull request by LahariDurgaKetha**
This is my submission for the registration form assignment. I have included the HTML and CSS code in the appropriate folder.

### CODE REVIEW

**Comment by salma2vec** [comment]
Hi there! 
I noticed that you have submitted a PNG file in the assignment folder. Please delete it and please upload the HTML code in the appropriate folder. 

Also, here are a 2 tiny suggestions to improve your code:
1. Instead of using a select dropdown for programs, consider using a `datalist` as it gives users the ability to easily input custom values.
2. For the email field, it is recommended to use the "email" input type rather than text as it ensures that only valid email addresses can be entered.

Overall, your code looks good! Keep up the good work! :)

**Comment by LahariDurgaKetha** [comment]
I am not able to delete the PNG file. I think I have uploaded the code in Assignment folder only right?

**Comment by salma2vec** [comment]
Yes. Just that change.

**Comment by LahariDurgaKetha** [comment]
yeah.. Thanks

**Comment by salma2vec** [comment]
Screenshot 2023-01-29 at 11 18 10 PM delete the image. And, the code -> reupload in the folder~

**Comment by LahariDurgaKetha** [comment]
I updated the dropdown and used datalist

**Comment by LahariDurgaKetha** [comment]
I have reuploaded the folder

**Comment by salma2vec** [comment]
LGTM. That's a wrap!

**Pull request merged**
