### PR TITLE
assignement 1 22BCE9396

### PR DESCRIPTION
**Pull request by HARSHILd11**
[ASSIGNEMENT 22BCE9396.docx](https://github.com/gdsc-vitap/Web-Development-Workshop/files/10532214/ASSIGNEMENT.22BCE9396.docx)
[ASSIGNEMENT 22BCE9396.pdf](https://github.com/gdsc-vitap/Web-Development-Workshop/files/10532215/ASSIGNEMENT.22BCE9396.pdf)

### CODE REVIEW

**Comment by salma2vec** [comment]
Hey there,
Thanks for submitting your work, but instead of attaching a PDF file, could you please upload the code directly into the assignment folder? This would make it easier for us to review and also keep all the relevant materials in one place. 
Let me know if you need any help with this. Looking forward to your updated submission. 
Thank you!

**Comment by HARSHILd11** [comment]
i am using git hub first time so can you plese specify where exactly and how to upload my code

**Comment by salma2vec** [comment]
I would like to suggest using the `reset` and `submit` button types. This will give the buttons a more defined purpose and improve the user experience. 
Please make these smol modifications so that I can review and merge at the earliest. Keep up the great work!

**Comment by HARSHILd11** [comment]
Hello mam ,I did not receive the certificate for the workshop ?

**Pull request closed without merging**
